# Site settings
title: A.P
baseurl: "/ap"
url: "https://bogyeom0922.github.io"
google_analytics: # Tracking ID, e.g. "UA-000000-01"

# Author
author:
  name: 박보겸
  desc: 팀과 함께 성장하고, 코드에 몰입하는 백엔드 개발자
  email: pbk0398@gmail.com
  selfie: assets/img/profile_img.JPEG
  website: https://velog.io/@pbk0398/posts


# social
social:
  email: true
  behance:
  bitbucket:
  dribbble:
  facebook: people/박보겸/pfbid02USLBiWV4wrw8itnmFZ7uFFnfY9yaonNZo2nBLNMusHz9rvaLYoCMLkbeBwNJH92yl/
  flickr:
  github: bogyeom0922
  google_plus:
  instagram:
  keybase:
  linkedin: https://www.linkedin.com/in/kssim/ 
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:
  steam:
  tumblr:
  gitlab:
  twitter: Test
  vimeo:
  wordpress:
  youtube:
  default_txt: "Follow On"
  

# Build settings
markdown: kramdown

# Assets
sass:
  sass_dir: _sass
  style: compressed

# Gems
plugins:
  - jekyll-paginate

# Permalinks
permalink: /:year-:month-:day/:title
paginate_path: "/portfolio/page:num/"
paginate: 5
exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "*.gem"
  - "LICENSE"
  - "READE.md"
  - "screenshot.png"
