# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: 박보겸
title: 팀과 함께 성장하고, 코드에 몰입하는 백엔드 개발자
email: pbk0398@gmail.com
website: https://dingco-ringco.tistory.com/

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username: bogyeom0922
facebook_username: people/박보겸/pfbid02USLBiWV4wrw8itnmFZ7uFFnfY9yaonNZo2nBLNMusHz9rvaLYoCMLkbeBwNJH92yl/

# About Section
# about_title: About Me
about_profile_image: images/profile_img.JPEG
about_content: |
  다양한 팀 프로젝트를 통해 **Node.js, Spring Boot, Java, MySQL, MongoDB, Python, AWS** 등을 활용하여 실제 서비스 개발을 수행해 왔으며, 이를 바탕으로 **RESTful API 설계**, **데이터베이스 구축 및 최적화**, **웹 서비스 배포 및 운영**까지 가능합니다.

  또한, AWS EC2, RDS를 이용한 배포 경험과 GitHub Actions, Docker를 활용한 자동화 경험을 통해 **실제 운영 환경에서의 서비스 구축**과 **지속적 배포 환경 구성**을 할 수 있습니다.

  프론트엔드 구현 경험도 갖추고 있어, UI 설계 및 사용자 경험 개선을 위한 **웹 전체 구조 개발**이 가능하며, 기능 구현을 넘어서 **유지보수성과 확장성**을 고려한 리팩터링도 지속적으로 실천해 왔습니다.

  **소통과 협업**을 중시하며 Git 기반의 버전 관리, 코드 리뷰, 문서화 등 협업 문화를 적극 실천하고 있습니다.

content:
  - title: Education
    layout: list
    content:
      - layout: top
        title: 건국대학교 글로컬캠퍼스
        caption: 2020.03 - 2024.02
        sub_title: ICT융합공학부 소프트웨어전공
        description: |
          C, C++, Python, R, Java, Javascript, UNIX 등 다양한 프로그래밍 언어를 학습하였으며, 특히 JavaScript와 Node.js를 이용한 웹 개발 및 서버 구축 프로젝트 경험이 있습니다.

          또한, 팀 프로젝트를 통해 협업 능력을 키웠고, 데이터 수집 및 분석을 위한 Python과 R을 활용한 경험도 갖추었습니다.  

  - title: Projects & Experience
    layout: list
    content:
      - layout: top
        title: MiTi
        link:
          - https://github.com/bogyeom0922/MiTi
        sub_title: 맞춤형 음악 추천 기능을 제공하는 음악 스트리밍 서비스
        caption: 2024.03 ~ 2024.10
        quote: >-
          개인 맞춤형 추천 알고리즘 개발, AWS 기반 배포 및 사용자 중심 UI 구현 경험을 통해 전반적인 웹 서비스 개발 및 운영 역량을 쌓았습니다.
        description: |
          **Spotify를 이용한 음악 크롤링 개선**
            - 수동으로 음악 ID를 입력하던 방식을 API 기반 카테고리 자동화로 개선하여 크롤링 속도 향상
            - CSV 저장 전 중복 음악 제거 및 국내 재생 가능 여부 검사 추가
            - API 요청 제한을 고려해 카테고리, 플레이리스트, 음악 개수 제한 및 요청 간 시간차 적용

          **MySQL과 Python을 연동한 개인 맞춤형 음악 추천 알고리즘**
            - 사용자의 재생 기록 기반 개인화 추천 제공
            - 코사인 유사도 계산을 통해 최적화된 유사 음악 추천
            - 추천 알고리즘은 재생 시마다 리프레시하여 사용자의 취향 변화를 반영
            - 유사 음악 특성 그룹핑으로 추천 정확도 향상

          **Spring Boot를 이용한 스트리밍 사이트 구현**
            - 앨범별 팔로워, 아티스트, 장르, 음악 목록 조회 기능 제공
            - 댓글 작성 및 조회 기능으로 사용자 간 소통 지원
            - 공유, 재생목록 추가, 좋아요 기능을 아코디언 메뉴로 제공하여 사용자 편의성 강화
            - Twitter, Band, Facebook 공유 및 링크 복사 기능 포함
            - 사용자별 재생목록 생성 및 음악 추가 기능 구현

          **CSS와 JavaScript를 활용한 직관적인 UI 설계**
            - 음악 재생바 및 재생 화면 토글을 직관적이고 깔끔하게 디자인
            - 기능별 버튼 크기 조절로 사용 편의성 증대
            - UI 요소별 범위 및 움직임 조정으로 이용 편의성 확보

          **AWS 기반 배포 및 운영**
            - AWS EC2 인스턴스에서 서버 배포 및 운영
            - AWS RDS를 통한 MySQL 데이터베이스 관리

          - 현재 재생 중인 음악과 유사한 음악을 자동으로 재생목록에 추가
          - OAuth2 기반 소셜 로그인 구현 (Spotify 계정 인증)
          - 비로그인 사용자의 접근 제한 처리

          🔗 [MiTi 프로젝트 개발 과정 보러가기](https://dingco-ringco.tistory.com/11)

          ---

      - layout: top
        title: EatToday
        link: https://github.com/bogyeom0922/EatToday
        sub_title: 메뉴와 음식점을 추천해주는 서비스
        caption: 2023.07 ~ 2023.10 / 2024.05 ~
        quote: >-
          실시간 채팅, JWT 인증, CI/CD 등 실무에 가까운 기능 구현을 통해 전체 시스템 아키텍처 설계 및 운영 경험을 확보했습니다.
        description: |
          **카카오맵을 이용한 음식점 크롤링**
            - 지역별 음식점 정보를 구, 카테고리별로 분리하여 효율적으로 수집하고 MySQL 데이터베이스에 저장

          **Spring Boot를 활용한 음식점 정보 제공 서비스 구현**
            - 음식점 상세 정보 조회 및 사용자 리뷰 작성, 조회, 수정, 삭제 기능 지원
            - 사용자와 식당 관계자 간 실시간 채팅 기능 구현 중

          **사용자 간 실시간 채팅 기능 개발**
            - WebSocket과 STOMP, SockJS 기반 실시간 양방향 통신 구현
            - 채팅 메시지 전송 시 sender, receiver, roomId, sentAt 등 메타정보 처리
            - 메시지 DB 저장 및 마이페이지에서 이전 채팅 내역 조회 가능
            - 메시지 브로드캐스트, 채팅방별 구독, 인증된 사용자 기반 메시지 전송 처리 구조 설계

          **CSS와 JavaScript를 활용한 직관적인 UI 설계**
            - 모든 연령층이 쉽게 사용할 수 있도록 직관적이고 반응형 UI 구현
            - 로그인, 회원가입, 아이디/비밀번호 찾기 기능을 레이어 팝업으로 구현하여 UX 개선
            - 음식점 위치를 지도에 시각적으로 표시해 탐색 편의성 향상
            - 전체 프론트엔드 과정을 직접 설계 및 구현

          **AWS 기반 서비스 배포 및 운영**
            - AWS RDS 기반 MySQL 데이터베이스 관리
            - EC2 인스턴스를 활용한 안정적인 서버 운영 환경 구축
            - Docker, GitHub Actions를 활용한 CI/CD 구성으로 실시간 배포 자동화

          **기타 개발 요소**
            - JUnit 기반 테스트 코드 작성으로 코드 안정성 확보

          - 채팅방 목록 조회 기능 및 유저 간 채팅방 재접속 처리 구현
          - JWT 기반 인증 로직 구현 및 세션 관리
          - 회원가입 시 이메일 중복 확인 기능 포함
          - 마이페이지에서 사용자가 작성한 리뷰 내역 조회 기능 구현

          ---

      - layout: top
        title: Text Me Merry Christmas
        link: https://github.com/bogyeom0922/text_me_merry_christmas
        sub_title: 크리스마스를 위한 미니홈피(SNS) 제작
        caption: 2022.10 ~ 2022.12 / 2024.3 ~
        quote: >-
          Node.js와 MongoDB 기반의 서버 구성과 테마 중심 UI 설계를 통해 사용자 경험과 데이터 구조를 모두 고려한 개발 역량을 쌓았습니다.
        description: |
          **크리스마스 분위기를 강조한 BGM 제공**
            - 메인 페이지에서 기본 BGM 재생
            - 마이페이지에서 추천 BGM 선택 및 재생

          **크리스마스 카드로 사용자 간 소통 기능 구현**
            - 다양한 카드 디자인 제공 및 작성 가능
            - 사용자가 받은 크리스마스 카드를 마이페이지에서 조회
            - 트리 장식 및 소원 작성 기능
            - 사용자가 작성한 소원을 익명으로 트리 장식에 추가
            - 모든 사용자의 소원을 메인 페이지에서 조회 가능

          **Node.js와 MongoDB를 활용한 서버 및 데이터베이스 구현**
            - 사용자 정보, 카드 내역, 소원 데이터를 MongoDB에 저장 및 관리
            - RESTful API를 활용한 프론트-백엔드 간 데이터 통신 구현

          **CSS와 JavaScript로 구현한 크리스마스 테마 UI**
            - 크리스마스 분위기를 강조한 인터페이스 설계
            - 디데이와 달력을 추가해 사용자 경험 향상

          - 사용자가 원하는 날짜로 크리스마스 D-Day 설정 가능
          - 카드 발송 시 알림 팝업을 통해 사용자 피드백 제공

          ---

      - layout: top
        title: Woowa Techcourse Pre-Course
        link: https://github.com/bogyeom0922/java-convenience-store-7-bogyeom0922
        sub_title: 객체지향 프로그래밍 원칙과 테스트 코드 작성 기반의 문제 해결 프로젝트
        caption: 2024.10 ~ 2022.11
        quote: >-
          객체지향 원칙과 테스트 코드 작성에 집중한 프로젝트로, 안정성과 유지보수성을 고려한 개발 역량을 함양했습니다.
        description: |
          **객체 지향 프로그래밍 원칙 준수**
            - MVC 패턴에 따라 클래스와 메서드 분리 및 구조화
            - 다양한 예외 상황을 고려한 안전한 코드 작성

          **테스트 코드 작성 및 코드 리뷰를 통한 개선**
            - 단위 테스트를 통해 숨겨진 오류를 검증 및 해결
            - 코드 리뷰를 통해 다른 지원자와의 상호 학습 및 성장
          
          **개발 표준 학습**
            - 자바 컨벤션 및 일관성 있는 커밋 메시지 작성 규칙 학습

          🔗 [진행 과정 중 작성한 회고록](https://dingco-ringco.tistory.com/8)

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag
