# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: 박보겸
title: 팀과 함께 성장하고, 코드에 몰입하는 백엔드 개발자
email: pbk0398@gmail.com
website: https://velog.io/@pbk0398/posts

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: 
github_username:  bogyeom0922
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
facebook_username: 100015180496745
# flickr_username: jekyll
# instagram_username: jameswgrant
# linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000


# Additional icon links
additional_links:
- title: itsgoingto.be
  icon: fas fa-globe
  url: https://velog.io/@pbk0398/posts
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/IMG_4385.jpg
about_content: | # this will include new lines to allow paragraphs
  백엔드 개발자로서 여러 팀 프로젝트에 참여하며 기초부터 다양한 기술을 익혔습니다. Node.js, SpringBoot, Java, MySQL, Python, AWS 등을 사용한 백엔드 개발과 간단한 프론트엔드 작업을 통해 실제 서비스를 개발하는 경험을 쌓았습니다.

  저는 팀원들과의 소통과 협업을 가장 중요하게 생각합니다. 개발 과정에서 기술적인 문제 해결뿐만 아니라, 팀의 목표를 달성하고 모두가 함께 성장할 수 있도록 돕는 데 큰 가치를 둡니다. 새로운 문제를 해결하며 팀의 목표를 함께 이루어나가는 과정에서 협업의 중요성을 깨닫고, 모두가 함께 성장하는 즐거움을 느꼈습니다.

  단순히 기능을 완성하는 데 그치지 않고, 지속적으로 코드를 리팩토링하며 확장성과 유지보수성이 뛰어난 백엔드 아키텍처를 설계하는 데 몰입해왔습니다. 이런 경험을 통해 더 나은 개발자로 성장해 나가고 있습니다.

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Super awesome project
        link: github.com/sproogen
        # link_text: Project Website
        additional_links:
          - title:  sproogen/modern-resume-theme
            icon: fab fa-github
            url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.
      - layout: left
        title: MiTi
        link: https://github.com/bogyeom0922/MiTi
        # link_text: boringcompany.com
        sub_title: Senior Network System Administrator
        caption: November 2017 - Present
        quote: >
          Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.

      - layout: left
        title: EatToday
        link: https://github.com/bogyeom0922/EatToday
        # link_text: boringcompany.com
        sub_title: Senior Network System Administrator
        caption: November 2017 - Present
        quote: >
          Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.

      - layout: left
        title: Text Me Merry Christmas
        link: https://github.com/bogyeom0922/sns-for-christmas
        # link_text: boringcompany.com
        sub_title: Senior Network System Administrator
        caption: November 2017 - Present
        quote: >
          Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.

      - layout: left
        title: 우아한 테크코스_프리코스
        # link_text: boringcompany.com
        sub_title: Senior Network System Administrator
        caption: November 2017 - Present
        description: | # this will include new lines to allow paragraphs
            Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
     content:
      - layout: left
        title: 건국대학교 글로컬캠퍼스
        caption: 2020.3 - 2024.2
        sub_title: ICT융합공학부 소프트웨어전공
        description: | # this will include new lines to allow paragraphs
          C, C++, Python, R, Java, Javascript, UNIX 등 다양한 프로그래밍 언어를 학습하였으며, 
          특히 JavaScript와 Node.js를 이용한 웹 개발 및 서버 구축 프로젝트 경험이 있습니다.
          또한, 팀 프로젝트를 통해 협업 능력을 키웠고, 데이터 수집 및 분석을 위한 Python과 R을 활용한 
          실무 경험도 갖추었습니다.

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag