# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: 박보겸
title: 팀과 함께 성장하고, 코드에 몰입하는 백엔드 개발자
email: pbk0398@gmail.com
website: https://velog.io/@pbk0398/posts

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username: bogyeom0922
facebook_username: people/박보겸/pfbid02USLBiWV4wrw8itnmFZ7uFFnfY9yaonNZo2nBLNMusHz9rvaLYoCMLkbeBwNJH92yl/

# About Section
# about_title: About Me
about_profile_image: images/profile_img.JPEG
about_content: |
  다양한 팀 프로젝트를 통해 **Node.js, Spring Boot, Java, MySQL, Python, AWS 등 여러 기술**을 익혔으며, 백엔드 개발과 간단한 프론트엔드 작업을 통해 실제 서비스 개발 경험을 쌓았습니다

  저는 기술적 문제 해결뿐만 아니라, **팀원들과의 소통과 협업**을 중요하게 생각합니다. 개발 과정에서 협업을 통해 목표를 달성하고 함께 성장하는 경험을 소중히 여기며 이를 통해 협업의 가치를 깨달았습니다.

  기능 구현에만 그치지 않고, 지속적으로 **코드를 리팩토링**하며 **확장성과 유지보수성을 고려한 설계**를 지향하고 있습니다. 이러한 노력을 통해 더 나은 개발자로 성장하고 있습니다.


content:
  - title: Projects & Experience
    layout: list
    content:
      - layout: top
        title: MiTi
        link: https://github.com/bogyeom0922/MiTi
        sub_title: 맞춤형 음악 추천 기능을 제공하는 음악 스트리밍 서비스
        caption: 2024.03 ~ 2024.10
        quote: >
          
        description: |
          **Spotify를 이용한 음악 크롤링**
            - 끊김 없는 음악 재생을 위해 재생 가능한 국가를 지정하여 음악 끊김 문제를 개선
            - 중복된 음악이 저장되지 않도록 검토 과정을 추가

          **MySQL과 Python을 연동하여 개인 맞춤형 음악 추천 알고리즘 제작**
            - 사용자가 재생한 음악 기록을 기반으로 개인화된 음악 추천 제공
            - 변화하는 취향에 맞게 재생할 때마다 추천 알고리즘을 리프레시
            - 음악 재생 시 끊김 없이 재생할 수 있도록 유사한 음악을 자동으로 재생목록에 추가
            - 장르별로 각 장르의 특징에 맞는 음악적 특성을 이용해 장르별 음악 재생목록 제공
            - 최적화된 추천 알고리즘을 위해 음악의 유사한 특성끼리 그룹으로 묶어 코사인 유사도를 계산하여 최적화된 유사 음악 추천

          **Spring Boot를 이용한 스트리밍 사이트 구현**
            - 각 앨범별로 팔로워, 아티스트, 장르, 음악 목록과 같은 상세 정보를 조회
            - 사용자 간 소통을 위한 댓글 작성 및 조회 기능 구현
            - 각 음악 별 공유, 재생목록 추가, 좋아요와 같은 소기능을 제공하는 아코디언 메뉴 개발로 사용자 편의성 향상
            - Twitter, Band, Facebook에 공유가 가능하며, 링크 복사 기능 추가
            - 자신만의 재생목록에 음악을 추가할 수 있고, 새로운 재생목록을 즉시 생성하여 음악을 추가할 수 있도록 구현

          **CSS와 JavaScript를 활용한 직관적인 UI 설계**
            - 음악 재생바와 재생 화면 토글이 직관적이고 깔끔하게 보이도록 디자인
            - 각 기능의 버튼마다 중요도에 따라 이미지 크기를 다르게 설정하여 서비스 이용의 어려움을 최소화
            - 이용에 불편함이 없도록 요소별 범위나 움직임 조정

          **AWS를 이용한 배포 및 서비스 운영**
            - AWS EC2 인스턴스를 사용하여 서버를 배포하고 서비스 운영
            - AWS RDS를 이용한 MySQL 데이터베이스 운영
          
          ___
      
      - layout: top
        title: EatToday
        link: https://github.com/bogyeom0922/EatToday
        sub_title: 메뉴와 음식점을 추천해주는 서비스
        caption: 2023.07 ~
        quote: >
          
        description: |
          **카카오맵을 이용한 음식점 크롤링**
            - 지역별 음식점 정보를 구, 메뉴별로 분리하여 효율적으로 수집하고 MySQL 데이터베이스에 저장

          **음식점 추천 기능 구현**
            - 사용자가 선택한 카테고리 내에서 랜덤으로 음식점 추천

          **Spring Boot를 활용한 음식점 정보 제공 서비스 구현**
            - 음식점의 상세 정보 조회 및 사용자 리뷰 작성, 조회, 수정, 삭제 기능 지원

          **CSS와 JavaScript를 활용해 직관적인 UI 설계**
            - 모든 연령층이 쉽게 사용할 수 있도록 직관적이고 반응형 UI 구현 
            -	로그인, 회원가입, 아이디/비밀번호 찾기 기능을 레이어 팝업 방식으로 최적화

          **AWS를 이용한 배포 및 서비스 운영**
            - AWS RDS 기반 MySQL 데이터베이스 관리 
            -	안정적인 서버 운영을 위해 AWS EC2 인스턴스 활용

          ___

      - layout: top
        title: Text Me Merry Christmas
        link: https://github.com/bogyeom0922/text_me_merry_christmas
        sub_title: 크리스마스를 위한 미니홈피(SNS) 제작
        caption: 2022.10 ~ 2022.12
        quote: >
          
        description: |
          **크리스마스 분위기를 강조한 BGM 제공**
            - 메인 페이지에서 기본 BGM 재생 
            -	마이페이지에서 추천 BGM 선택 및 재생

          **크리스마스 카드로 사용자 간 소통 기능 구현**
            - 크리스마스 카드로 사용자 간 소통 기능 구현
            - 다양한 카드 디자인 제공 및 작성 가능
            - 사용자가 받은 크리스마스 카드를 마이페이지에서 조회
            -	트리 장식 및 소원 작성 기능
            -	사용자가 작성한 소원을 익명으로 트리 장식에 추가
            -	모든 사용자의 소원을 메인 페이지에서 조회 가능

          **CSS와 JavaScript로 구현한 크리스마스 테마 UI**
            - 크리스마스 분위기를 강조한 인터페이스 설계
            -	디데이와 달력을 추가해 사용자 경험 향상

          ___

      - layout: top
        title: Woowa Techcourse Pre-Course
        link: https://github.com/bogyeom0922/java-convenience-store-7-bogyeom0922
        sub_title: 객체지향 프로그래밍 원칙과 테스트 코드 작성 기반의 문제 해결 프로젝트
        caption: 2024.10 ~ 2022.11
        quote: >

        description: |
          **객체 지향 프로그래밍 원칙 준수**
            - MVC 패턴에 따라 클래스와 메서드 분리 및 구조화
            -	다양한 예외 상황을 고려한 안전한 코드 작성

          **테스트 코드 작성 및 코드 리뷰를 통한 개선**
            -	단위 테스트를 통해 숨겨진 오류를 검증 및 해결
            -	코드 리뷰를 통해 다른 지원자와의 상호 학습 및 성장
              
          **개발 표준 학습**
            -	자바 컨벤션 및 일관성 있는 커밋 메시지 작성 규칙 학습


  - title: Education
    layout: list
    content:
      - layout: top-middle
        title: 건국대학교 글로컬캠퍼스
        caption: 2020.3 - 2024.2
        sub_title: ICT융합공학부 소프트웨어전공
        description: |
          C, C++, Python, R, Java, Javascript, UNIX 등 다양한 프로그래밍 언어를 학습하였으며, 
          특히 JavaScript와 Node.js를 이용한 **웹 개발 및 서버 구축 프로젝트 경험**이 있습니다.
          또한, 팀 프로젝트를 통해 **협업 능력**을 키웠고, 데이터 수집 및 분석을 위한 Python과 R을 활용한 
          경험도 갖추었습니다.

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag